[package]
name = "pipefog"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.*"
serde_json = "1.*"
regex = "*"
lazy_static = "1.*"
hex = "0.4"

[[bin]]
name = "syllable_frequency"
path = "src/bin/syllable_frequency.rs"
